@startuml Souvenir Manajemen.Delete
mainframe **sd** Manajemen Souvenir.Delete
actor "Admin/SuperAdmin"  as User
boundary "Home View" as HomeView
boundary "Manajemen User View" as SouvenirView
control SouvenirController 
entity Souvenir as SouvenirModel

autonumber
' autoactivate on
skinparam SequenceMessageAlignment center

activate User
activate HomeView
User->HomeView: souvenir()
deactivate User
HomeView->SouvenirController: index()
deactivate HomeView
activate SouvenirController
activate SouvenirView
SouvenirController->SouvenirView: view(Souvenir.index)
activate User
User->SouvenirView: delete(souvenir)
SouvenirView->SouvenirController: delete(souvenir)
SouvenirController->SouvenirModel: deleteUser(souvenir)
SouvenirModel-->SouvenirController: success
SouvenirController-->SouvenirView: success
deactivate SouvenirController
deactivate SouvenirView
deactivate User



@enduml