@startuml Destinasi Manajemen.Delete
mainframe **sd** Manajemen Destinasi.delete
actor "Admin/SuperAdmin"  as User
boundary "Home View" as HomeView
boundary "Manajemen User View" as DestinasiView
control DestinasiController 
entity Destinasi as DestinasiModel

autonumber
' autoactivate on
skinparam SequenceMessageAlignment center

activate User
activate HomeView
User->HomeView: destinasi()
deactivate User
HomeView->DestinasiController: index()
deactivate HomeView
activate DestinasiController
activate DestinasiView
DestinasiController->DestinasiView: view(Destinasi.index)
activate User
User->DestinasiView: delete(destinasi)
DestinasiView->DestinasiController: delete(destinasi)
DestinasiController->DestinasiModel: deleteUser(destinasi)
DestinasiModel-->DestinasiController: success
DestinasiController-->DestinasiView: success
deactivate DestinasiController
deactivate DestinasiView
deactivate User



@enduml