@startuml Destinasi Manajemen.Create
mainframe **sd** Manajemen Destinasi.Create
actor "Admin/SuperAdmin"  as User
boundary "Home View" as HomeView
boundary "Manajemen Destinasi View" as DestinasiView
control DestinasiController 
entity Destinasi as DestinasiModel

autonumber
' autoactivate on
skinparam SequenceMessageAlignment center

activate User
activate HomeView
User->HomeView: destinasi()
deactivate User
HomeView->DestinasiController: index()
deactivate HomeView
activate DestinasiController
activate DestinasiView
DestinasiController-->DestinasiView: view(Destinasi.index)
activate User
User->DestinasiView: create()
DestinasiView->DestinasiController : create()
DestinasiController --> DestinasiView: view(Destinasi.create)
User->DestinasiView: input(datadestinasi)
DestinasiView->DestinasiController: create(datadestinasi)
activate DestinasiModel
DestinasiController->DestinasiModel: insertDestinasi(destinasi)
DestinasiModel-->DestinasiController: success
DestinasiController-->DestinasiView: success
deactivate DestinasiModel
deactivate DestinasiView
deactivate User

@enduml