@startuml User Manajemen.Update
mainframe **sd** Manajemen User.Update
actor "Admin/SuperAdmin"  as User
boundary "Home View" as HomeView
boundary "Manajemen User View" as UsersView
control UserController 
entity Users as UserModel

autonumber
' autoactivate on
skinparam SequenceMessageAlignment center

activate User
activate HomeView
User->HomeView: users()
deactivate User
HomeView->UserController: index()
deactivate HomeView
activate UserController
activate UsersView
UserController-->UsersView: view(users.index)
activate User
User->UsersView: update()
UsersView->UserController : update()
UserController --> UsersView: view(users.update)
User->UsersView: input(datauser)
UsersView->UserController: update(datauser)
activate UserModel
UserController->UserModel: updateUser(user)
UserModel-->UserController: success
UserController-->UsersView: success
deactivate UserModel
deactivate UsersView
deactivate User

@enduml