@startuml User Manajemen.Delete
mainframe **sd** Manajemen User.Delete
actor "Admin/SuperAdmin"  as User
boundary "Home View" as HomeView
boundary "Manajemen User View" as UsersView
control UserController 
entity Users as UserModel

autonumber
' autoactivate on
skinparam SequenceMessageAlignment center

activate User
activate HomeView
User->HomeView: users()
deactivate User
HomeView->UserController: index()
deactivate HomeView
activate UserController
activate UsersView
UserController->UsersView: view(Users.index)
activate User
User->UsersView: delete(user)
UsersView->UserController: delete(user)
UserController->UserModel: deleteUser(user)
UserModel-->UserController: success
UserController-->UsersView: success
deactivate UserController
deactivate UsersView
deactivate User



@enduml