@startuml AdBanner Manajemen.Delete
mainframe **sd** Manajemen AdBanner.delete
actor "Admin/SuperAdmin"  as User
boundary "Home View" as HomeView
boundary "Manajemen User View" as AdBannerView
control AdBannerController 
entity AdBanner as AdBannerModel

autonumber
' autoactivate on
skinparam SequenceMessageAlignment center

activate User
activate HomeView
User->HomeView: adbanner()
deactivate User
HomeView->AdBannerController: index()
deactivate HomeView
activate AdBannerController
activate AdBannerView
AdBannerController->AdBannerView: view(AdBanner.index)
activate User
User->AdBannerView: delete(adbanner)
AdBannerView->AdBannerController: delete(adbanner)
AdBannerController->AdBannerModel: deleteUser(adbanner)
AdBannerModel-->AdBannerController: success
AdBannerController-->AdBannerView: success
deactivate AdBannerController
deactivate AdBannerView
deactivate User



@enduml