@startuml Lihat Rekomendasi
mainframe **sd** Melihat Rekomendasi
actor "User" as User
control HomeController 
boundary "Home View" as HomeView
entity Recomendation as RecomendationModel

autonumber
' autoactivate on
skinparam SequenceMessageAlignment center
activate User
User->HomeController : boot()
activate HomeController
activate HomeView
HomeController->HomeView: build()
activate RecomendationModel
HomeController->RecomendationModel : fetch()
RecomendationModel->HomeView : return(recomendations)

@enduml