@startuml Package Manajemen.Delete
mainframe **sd** Manajemen Package.Delete
actor "Admin/SuperAdmin"  as User
boundary "Home View" as HomeView
boundary "Manajemen User View" as PackageView
control PackageController 
entity Package as PackageModel

autonumber
' autoactivate on
skinparam SequenceMessageAlignment center

activate User
activate HomeView
User->HomeView: package()
deactivate User
HomeView->PackageController: index()
deactivate HomeView
activate PackageController
activate PackageView
PackageController->PackageView: view(Package.index)
activate User
User->PackageView: delete(package)
PackageView->PackageController: delete(package)
PackageController->PackageModel: deleteUser(package)
PackageModel-->PackageController: success
PackageController-->PackageView: success
deactivate PackageController
deactivate PackageView
deactivate User



@enduml